<?php
// Include database connection
@include 'db_connection.php';
session_start();

// Handle form submissions
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (isset($_POST['add_supply']) || isset($_POST['edit_supply'])) {
        $drugHeaderID = $_POST['drug_header_id'];
        $vendorID = $_POST['vendor_id'];
        $quantity = $_POST['quantity'];
        $manufactureDate = $_POST['manufacture_date'];
        $expiryDate = $_POST['expiry_date'];

        if (isset($_POST['edit_supply'])) {
            $supplyID = $_POST['supply_id'];

            // Update existing supply
            $stmt = $conn->prepare("UPDATE drug_supply SET DrugHeaderID = ?, VendorID = ?, Quantity = ?, Manufacture_Date = ?, ExpiryDate = ? WHERE SupplyID = ?");
            $stmt->bind_param("ssisss", $drugHeaderID, $vendorID, $quantity, $manufactureDate, $expiryDate, $supplyID);
        } else {
            // Insert new supply (SupplyID will be auto-generated by the trigger)
            $stmt = $conn->prepare("INSERT INTO drug_supply (DrugHeaderID, VendorID, Quantity, Manufacture_Date, ExpiryDate) VALUES (?, ?, ?, ?, ?)");
            $stmt->bind_param("ssiss", $drugHeaderID, $vendorID, $quantity, $manufactureDate, $expiryDate);
        }

        if ($stmt->execute()) {
            echo "<script>alert('Supply successfully " . (isset($_POST['edit_supply']) ? "updated" : "added") . "!');
                window.location.href = 'drug_inventory.php';
            </script>";
        } else {
            echo "<script>alert('Error: " . $conn->error . "');</script>";
        }
        $stmt->close();
    }

    // Handle delete supply request
    if (isset($_POST['delete_supply'])) {
        $supplyID = $_POST['supply_id'];

        $stmt = $conn->prepare("DELETE FROM drug_supply WHERE SupplyID = ?");
        $stmt->bind_param("s", $supplyID);

        if ($stmt->execute()) {
            echo "<script>alert('Supply successfully deleted!');
                window.location.href = 'drug_inventory.php';
            </script>";
        } else {
            echo "<script>alert('Error: " . $conn->error . "');</script>";
        }
        $stmt->close();
    }
}

// Fetch drug supply data excluding SupplyID
$query = "SELECT 
            ds.SupplyID,
            dh.Category_Name AS DrugName,
            v.Fullname AS VendorName,
            ds.Quantity,
            ds.Manufacture_Date,
            ds.ExpiryDate
          FROM 
            drug_supply ds
          JOIN 
            drug_header dh ON ds.DrugHeaderID = dh.DrugHeaderID
          JOIN 
            vendor v ON ds.VendorID = v.VendorID";
$result = mysqli_query($conn, $query);
?>


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Drug Stock Management</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&family=Poppins:wght@500;700&display=swap" rel="stylesheet">
    <style>
        /* General Styling */
        body {
            font-family: 'Poppins', sans-serif;
            margin: 0;
            padding: 0;
            background: linear-gradient(135deg, #ff9a3c, #f83600);
        }

        /* Sidebar */
        .sidebar {
            width: 250px;
            height: 100vh;
            background: linear-gradient(135deg, #ff9a3c, #f83600);
            color: white;
            position: fixed;
            top: 0;
            left: 0;
            display: flex;
            flex-direction: column;
            box-shadow: 2px 0 5px rgba(0, 0, 0, 0.1);
            border-radius: 0 20px 20px 0;
        }

        .sidebar a {
            text-decoration: none;
            color: white;
            padding: 15px 20px;
            display: block;
            font-size: 1.1em;
            transition: background-color 0.3s ease, color 0.3s ease;
        }

        .sidebar a:hover {
            background-color: rgba(255, 255, 255, 0.2);
            color: #ffd700;
        }

        /* Logo Styling */
        .logo {
            display: flex;
            align-items: center;
            gap: 10px;
            margin: 20px;
        }

        .logo-icon {
            background: linear-gradient(135deg, #ff9a3c, #f83600);
            width: 40px;
            height: 40px;
            display: flex;
            justify-content: center;
            align-items: center;
            border-radius: 50%;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        }

        .logo-icon i {
            color: white;
            font-size: 1.5em;
        }

        .logo h2 {
            font-size: 1.7em;
            font-weight: bold;
            color: #fdfcfb;
            margin: 0;
            font-family: 'Roboto', sans-serif;
            text-shadow: 1px 1px 5px rgba(0, 0, 0, 0.2);
        }

        /* Main Content Area */
        .content-wrapper {
            margin-left: 250px;
            padding: 20px;
            min-height: 100vh;
            background: white;
            border-radius: 10px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }

        /* Buttons */
        .btn {
            padding: 10px 15px;
            margin: 5px;
            border-radius: 5px;
            text-decoration: none;
            color: white;
            font-size: 0.9em;
            transition: background-color 0.3s ease;
        }

        .btn-primary {
            background-color: #28a745;
        }

        .btn-primary:hover {
            background-color: #218838;
        }

        .btn-warning {
            background-color: #ffc107;
        }

        .btn-warning:hover {
            background-color: #e0a800;
        }

        .btn-danger {
            background-color: #dc3545;
        }

        .btn-danger:hover {
            background-color: #c82333;
        }

        /* Table */
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        table th,
        table td {
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }

        table th {
            background-color: #f1f1f1;
        }

        table tr:hover {
            background-color: #f9f9f9;
        }
    </style>
</head>

<body>
    <!-- Sidebar -->
    <div class="sidebar">
        <div class="logo">
            <div class="logo-icon">
                <i class="fas fa-pills"></i>
            </div>
            <h2>Pharmacy Manager</h2>
        </div>
        <a href="index.php">Home</a>
        <a href="manage_drug.php">Manage Drugs</a>
        <a href="drug_inventory.php">Inventory</a>
        <a href="vendor.php">Vendor</a>
        <a href="report.php">Report</a>
        <a href="logout.php">Logout</a>
    </div>

    <!-- Main Content -->
    <div class="content-wrapper">
        <h1>Drug Stock Management</h1>
        <a href="#" class="btn btn-primary" onclick="openAddSupplyModal()">Add Supply</a>
        <table>
            <thead>
                <tr>
                    <th>Drug Name</th>
                    <th>Vendor Name</th>
                    <th>Quantity</th>
                    <th>Manufacture Date</th>
                    <th>Expiry Date</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
    <?php while ($row = mysqli_fetch_assoc($result)) { 
        $rowStyle = ($row['Quantity'] < 10) ? 'style="background-color: #ffcccc; color: red; font-weight: bold;"' : ''; // Conditional styling
    ?>
        <tr <?php echo $rowStyle; ?>>
            <td><?php echo htmlspecialchars($row['DrugName']); ?></td>
            <td><?php echo htmlspecialchars($row['VendorName']); ?></td>
            <td><?php echo htmlspecialchars($row['Quantity']); ?></td>
            <td><?php echo htmlspecialchars($row['Manufacture_Date']); ?></td>
            <td><?php echo htmlspecialchars($row['ExpiryDate']); ?></td>
            <td>
                <a href="#" class="btn btn-warning" onclick='openEditSupplyModal(<?php echo json_encode($row); ?>)'>Edit</a>
                <form method="post" style="display:inline;">
                    <input type="hidden" name="supply_id" value="<?php echo htmlspecialchars($row['SupplyID']); ?>">
                    <button type="submit" name="delete_supply" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this supply?');">Delete</button>
                </form>
            </td>
        </tr>
    <?php } ?>
</tbody>

        </table>
    </div>
</body>

</html>


    <!-- Add/Edit Supply Modal -->
<div id="supplyModal" style="display:none; background-color: rgba(0, 0, 0, 0.5); position: fixed; top: 0; left: 0; width: 100%; height: 100%; padding: 50px;">
    <div style="background: white; padding: 20px; border-radius: 10px; max-width: 500px; margin: auto;">
        <h2 id="modalTitle">Add Supply</h2>
        <form id="supplyForm" method="post" action="">
    <input type="hidden" name="supply_id" id="supplyId">
    <label>Drug Name:</label><br>
    <select name="drug_header_id" id="drugHeaderId" required>
        <option value="">Select Drug</option>
        <?php
        $drugQuery = "SELECT DrugHeaderID, Category_Name FROM drug_header";
        $drugResult = mysqli_query($conn, $drugQuery);
        while ($drug = mysqli_fetch_assoc($drugResult)) {
            echo "<option value='{$drug['DrugHeaderID']}'>{$drug['Category_Name']}</option>";
        }
        ?>
    </select><br><br>

    <label>Vendor Name:</label><br>
    <select name="vendor_id" id="vendorId" required>
        <option value="">Select Vendor</option>
        <?php
        $vendorQuery = "SELECT VendorID, Fullname FROM vendor";
        $vendorResult = mysqli_query($conn, $vendorQuery);
        while ($vendor = mysqli_fetch_assoc($vendorResult)) {
            echo "<option value='{$vendor['VendorID']}'>{$vendor['Fullname']}</option>";
        }
        ?>
    </select><br><br>

    <label>Quantity:</label><br>
    <input type="number" name="quantity" id="quantity" required><br><br>

    <label>Manufacture Date:</label><br>
    <input type="date" name="manufacture_date" id="manufactureDate" required><br><br>

    <label>Expiry Date:</label><br>
    <input type="date" name="expiry_date" id="expiryDate" required><br><br>

    <button type="submit" id="submitButton" name="add_supply" class="btn btn-primary">Add Supply</button>
    <button type="button" class="btn btn-danger" onclick="closeModal()">Cancel</button>
</form>

    </div>
</div>

<script>
    function openAddSupplyModal() {
        document.getElementById('modalTitle').innerText = 'Add Supply';
        document.getElementById('submitButton').innerText = 'Add Supply';
        document.getElementById('submitButton').name = 'add_supply';
        clearForm();
        document.getElementById('supplyModal').style.display = 'block';
    }

    function openEditSupplyModal(supply) {
    document.getElementById('modalTitle').innerText = 'Edit Supply';
    document.getElementById('submitButton').innerText = 'Update Supply';
    document.getElementById('submitButton').name = 'edit_supply';
    document.getElementById('supplyId').value = supply.SupplyID; // Hidden field
    populateForm(supply);
    document.getElementById('supplyModal').style.display = 'block';
}


    function closeModal() {
        document.getElementById('supplyModal').style.display = 'none';
    }

    function clearForm() {
        document.getElementById('drugHeaderId').value = '';
        document.getElementById('vendorId').value = '';
        document.getElementById('quantity').value = '';
        document.getElementById('manufactureDate').value = '';
        document.getElementById('expiryDate').value = '';
    }

    function populateForm(supply) {
        document.getElementById('drugHeaderId').value = supply.DrugHeaderID; // Use DrugHeaderID
        document.getElementById('vendorId').value = supply.VendorID;         // Use VendorID
        document.getElementById('quantity').value = supply.Quantity;
        document.getElementById('manufactureDate').value = supply.Manufacture_Date;
        document.getElementById('expiryDate').value = supply.ExpiryDate;
    }
</script>

